### ISSUE TITLE
Make portkey work with frozen java.security.* instances

### ISSUE THREAD

**Issue by viesti** [portkey-cloud/portkey#41]
A test that should provoke the problem is here:

https://github.com/portkey-cloud/portkey/blob/b014a4d9bfafabb972feaba90a3f04e425c02510/test/portkey/core_test.clj#L218

**Comment by cgrand** [comment]
Or `java.crypto`).

From what I do remember is that the actual classes are quite private and, as such, don't translate well between envs.

However since all theses objects are created by starting at a few static factories methods, one possible way to deal with that is to instrument these classes so as to trace (either in an external record or by using proxies) how each instance was created using the public API so as to able to reissue the same sequence of operations  to build equivalent instances on the target env.

**Comment by cgrand** [comment]
Error example:
```
Error loading class portkey.LambdaStub: java.lang.ExceptionInInitializerError
java.lang.ExceptionInInitializerError
at java.lang.Class.forName0(Native Method)
at java.lang.Class.forName(Class.java:348)
Caused by: com.esotericsoftware.kryo.KryoException: Encountered unregistered class ID: 27
Serialization trace:
keys (sun.security.ssl.EphemeralKeyManager)
ephemeralKeyManager (sun.security.ssl.SSLContextImpl$TLSContext)
context (sun.security.ssl.SSLSocketFactoryImpl)
socketfactory (org.apache.http.conn.ssl.SSLConnectionSocketFactory)
map (org.apache.http.config.Registry)
at com.esotericsoftware.kryo.util.DefaultClassResolver.readClass(DefaultClassResolver.java:137)
at com.esotericsoftware.kryo.Kryo.readClass(Kryo.java:693)
at com.esotericsoftware.kryo.serializers.ObjectField.read(ObjectField.java:118)
at com.esotericsoftware.kryo.serializers.FieldSerializer.read(FieldSerializer.java:540)
at com.esotericsoftware.kryo.Kryo.readObjectOrNull(Kryo.java:782)
at com.esotericsoftware.kryo.serializers.ObjectField.read(ObjectField.java:132)
at com.esotericsoftware.kryo.serializers.FieldSerializer.read(FieldSerializer.java:540)
at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:731)
at com.esotericsoftware.kryo.serializers.ObjectField.read(ObjectField.java:125)
at com.esotericsoftware.kryo.serializers.FieldSerializer.read(FieldSerializer.java:540)
at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:731)
at com.esotericsoftware.kryo.serializers.ObjectField.read(ObjectField.java:125)
at com.esotericsoftware.kryo.serializers.FieldSerializer.read(FieldSerializer.java:540)
at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:813)
at com.esotericsoftware.kryo.serializers.MapSerializer.read(MapSerializer.java:161)
at com.esotericsoftware.kryo.serializers.MapSerializer.read(MapSerializer.java:39)
at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:731)
at com.esotericsoftware.kryo.serializers.ObjectField.read(ObjectField.java:125)
at com.esotericsoftware.kryo.serializers.FieldSerializer.read(FieldSerializer.java:540)
at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:813)
at portkey.kryo$coll_serializer$fn__196$fn__197.invoke(kryo.clj:44)
at clojure.core$map$fn__5414$fn__5415.invoke(core.clj:2722)
at clojure.lang.Range.reduce(Range.java:180)
at clojure.core$transduce.invokeStatic(core.clj:6759)
at clojure.core$into.invokeStatic(core.clj:6775)
at clojure.core$into.invoke(core.clj:6763)
at portkey.kryo$coll_serializer$fn__196.invoke(kryo.clj:44)
at portkey.kryo$fn__189$fn__190.invoke(kryo.clj:36)
at portkey.SerializerStub.read(SerializerStub.java:32)
at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:813)
at portkey.kryo$unfreeze.invokeStatic(kryo.clj:212)
at portkey.kryo$unfreeze.invoke(kryo.clj:208)
at portkey.core$bootstrap$fn__16606.invoke(core.clj:205)
at portkey.LambdaStub.<clinit>(LambdaStub.java:23)
... 2 more
```

**Comment by cgrand** [comment]
So we need to start tracking from eg `SSLContext/getInstance`

**Comment by viesti** [comment]
For the record, I ran into this with following setup (the below output masks what's happening behind the scenes):

```clojure
0% cat deps.edn
{:deps {org.clojure/clojure {:mvn/version "1.9.0"}
        clj-http/clj-http {:mvn/version "3.8.0"}
        portkey/portkey {:mvn/version "0.1.0-SNAPSHOT"}}}

0% clj -Srepro
Clojure 1.9.0
user=> (require '[portkey.core :as pk])
nil
user=> (require '[clj-http.client :as http])
nil
user=> (defn google [in out ctx] (->> "https://www.google.com" http/get :body (spit out)))
#'user/google
user=> (pk/deploy! google "google" {:s3 {:bucket "tiuhti-portkey"}})
Zip size 4.5MB
"arn:aws:lambda:eu-west-1:xxxxx:function:google"
aws lambda invoke --function-name google out.log
{
    "StatusCode": 200,
    "FunctionError": "Unhandled",
    "ExecutedVersion": "$LATEST"
}
0% cat out.log|jq
{
  "errorMessage": "Attempting to call unbound fn: #'clj-http.core/request",
  "errorType": "java.lang.IllegalStateException",
  "stackTrace": [
    "clojure.lang.Var$Unbound.throwArity(Var.java:45)",
    "clojure.lang.AFn.invoke(AFn.java:32)",
    "clojure.lang.Var.invoke(Var.java:381)",
    "clj_http.client$wrap_request_timing$fn__4729.invoke(client.clj:1078)",
    "clj_http.client$wrap_async_pooling$fn__4737.invoke(client.clj:1111)",
    "clj_http.headers$wrap_header_map$fn__2947.invoke(headers.clj:147)",
    "clj_http.client$wrap_query_params$fn__4609.invoke(client.clj:812)",
    "clj_http.client$wrap_basic_auth$fn__4615.invoke(client.clj:835)",
    "clj_http.client$wrap_oauth$fn__4620.invoke(client.clj:852)",
    "clj_http.client$wrap_user_info$fn__4629.invoke(client.clj:872)",
    "clj_http.client$wrap_url$fn__4711.invoke(client.clj:1030)",
    "clj_http.client$wrap_decompression$fn__4380.invoke(client.clj:416)",
    "clj_http.client$wrap_input_coercion$fn__4533.invoke(client.clj:632)",
    "clj_http.client$wrap_additional_header_parsing$fn__4558.invoke(client.clj:687)",
    "clj_http.client$wrap_output_coercion$fn__4520.invoke(client.clj:576)",
    "clj_http.client$wrap_exceptions$fn__4327.invoke(client.clj:250)",
    "clj_http.client$wrap_accept$fn__4573.invoke(client.clj:730)",
    "clj_http.client$wrap_accept_encoding$fn__4580.invoke(client.clj:752)",
    "clj_http.client$wrap_content_type$fn__4567.invoke(client.clj:713)",
    "clj_http.client$wrap_form_params$fn__4676.invoke(client.clj:954)",
    "clj_http.client$wrap_nested_params$fn__4697.invoke(client.clj:988)",
    "clj_http.client$wrap_flatten_nested_params$fn__4706.invoke(client.clj:1012)",
    "clj_http.client$wrap_method$fn__4634.invoke(client.clj:888)",
    "clj_http.cookies$wrap_cookies$fn__1826.invoke(cookies.clj:131)",
    "clj_http.links$wrap_links$fn__3314.invoke(links.clj:63)",
    "clj_http.client$wrap_unknown_host$fn__4714.invoke(client.clj:1041)",
    "clj_http.client$request_STAR_.invokeStatic(client.clj:1214)",
    "clj_http.client$request_STAR_.invoke(client.clj:1207)",
    "clj_http.client$get.invokeStatic(client.clj:1220)",
    "clj_http.client$get.doInvoke(client.clj:1216)",
    "clojure.lang.RestFn.invoke(RestFn.java:410)",
    "user$google.invokeStatic(NO_SOURCE_FILE:3)",
    "user$google.invoke(NO_SOURCE_FILE:3)",
    "portkey.LambdaStub.handleRequest(LambdaStub.java:33)"
  ]
}
```

**Comment by cgrand** [comment]
The meaningful log is in cloud watch because the error occurs at init before request handling
